name: build-push

on:
  push:
    branches:
    - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # https://github.com/actions/setup-node
    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'

    # https://github.com/actions/setup-dotnet
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        
    - run: corepack enable # enable yarn @ node >= 16.10

    - name: dotnet publish
      run: dotnet publish "src/HttpToWebPush.Server/HttpToWebPush.Server.csproj" -c Release -o publish
      
    # https://github.com/docker/login-action
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/patrick-b6n/http-to-web-push:latest